config/routes.rb
Rails.application.routes.draw do
  get 'wowza/index'

  resources :streams

  root 'wowza#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stream.rb
class Stream < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/streams_controller.rb
require 'rubygems'
require 'json'
require 'rest-client'

class StreamsController < ApplicationController
  def new

  end
  def index
    RestClient.get(
      'https://api-sandbox.cloud.wowza.com/api/v1/live_streams/' + params[:id],
      :content_type => :json,
      :accept => :json,
      :'wsc-api-key' => @@wsc_api_key,
      :'wsc-access-key' => @@wsc_access_key
    ) { |response, request, result|
      case response.code
      when 301, 302, 307
        response.follow_redirection
      else
        data = JSON.parse(response)['live_stream']['source_connection_information']
        url = JSON.parse(response)['live_stream']['hosted_page_url']
        @stream = {
          id: JSON.parse(response)['live_stream']['id'],
          primary_server: data['primary_server'],
          host_port: data['host_port'],
          stream_name: data['stream_name'],
          hosted_page: url
        }
        render 'stream'
      end
    }
  end

  def create
    data = {live_stream: {
        name: params[:streams][:stream_name],
        transcoder_type: params[:streams][:transcoder_type],
        billing_mode: params[:streams][:billing_mode],
        broadcast_location: params[:streams][:broadcast_location],
        encoder: params[:streams][:encoder],
        delivery_method: params[:streams][:delivery_method],
        aspect_ratio_width: params[:streams][:aspect_ratio_width],
        aspect_ratio_height: params[:streams][:aspect_ratio_height],
        disable_authentication: true,
        hosted_page: true,
        hosted_page_description: params[:streams][:stream_name],
        hosted_page_title: params[:streams][:stream_name],
      }}
    RestClient.post(
      'https://api-sandbox.cloud.wowza.com/api/v1/live_streams',
      data.to_json,
      :content_type => :json,
      :accept => :json,
      :'wsc-api-key' => @@wsc_api_key,
      :'wsc-access-key' => @@wsc_access_key
    ) { |response, request, result|
      case response.code
      when 301, 302, 307
        response.follow_redirection
      else
        data = JSON.parse(response)['live_stream']['source_connection_information']
        url = JSON.parse(response)['live_stream']['hosted_page_url']
        @stream = {
          id: JSON.parse(response)['live_stream']['id'],
          primary_server: data['primary_server'],
          host_port: data['host_port'],
          stream_name: data['stream_name'],
          hosted_page: url
        }
        render 'stream'
      end
    }
  end
end

app/controllers/wowza_controller.rb
class WowzaController < ApplicationController
  def new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/helpers/wowza_helper.rb
module WowzaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wowza</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/streams/stream.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <h1>New Stream</h1>
        <div class='primary_server'>
            <h4>Primary Server:</h4>
            <code><%= @stream[:primary_server] %></code>
        </div>
        <div class='host_port'>
          <h4>Host Port:</h4>
          <code><%= @stream[:host_port] %></code>
        </div>
        <div class='stream_name'>
          <h4>Stream name:</h4>
          <code><%= @stream[:stream_name] %></code>
        </div>
        <div class='stream_url'>
          <h4>Stream hosted page:</h4>
          <% if @stream[:hosted_page] == 'in_progress' %>
            <p>Hosted page is being created, check back later.</p>
            <%= button_to "Check if ready", streams_path, method: :get, params: { id: @stream[:id] }, :class => 'btn btn-primary' %>
          <% else %>
            <code><%= @stream[:hosted_page] %></code>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/wowza/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <h1>New Stream</h1>
        <%= form_for :streams, url: streams_path do |f| %>
          <div class="form-group">
            <%= f.label :stream_name, :for => 'stream_name' %><br>
            <%= f.text_field :stream_name, :value => 'Awesome Stream!', :id => 'stream_name', :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :transcoder_type %><br>
            <%= f.select :transcoder_type, [['Transcoded','transcoded'],['Passthrough','passthrough']], {},  :class => 'form-control'  %>
          </div>

          <div class="form-group">
            <%= f.label :billing_mode %><br>
            <%= f.select :billing_mode, [['Pay_as_you_go','pay_as_you_go']], {},  :class => 'form-control'  %>
          </div>

          <div class="form-group">
            <%= f.label :broadcast_location %><br>
            <%=
              f.select :broadcast_location,
              [
                ['asia_pacific_australia','asia_pacific_australia'],
                ['asia_pacific_india','asia_pacific_india'],
                ['asia_pacific_japan','asia_pacific_japan'],
                ['asia_pacific_s_korea','asia_pacific_s_korea'],
                ['asia_pacific_singapore','asia_pacific_singapore'],
                ['asia_pacific_taiwan','asia_pacific_taiwan'],
                ['eu_belgium','eu_belgium'],
                ['eu_germany','eu_germany'],
                ['eu_ireland','eu_ireland'],
                ['south_america_brazil','south_america_brazil'],
                ['us_central_iowa','us_central_iowa'],
                ['us_east_s_carolina','us_east_s_carolina'],
                ['us_east_virginia','us_east_virginia'],
                ['us_west_california','us_west_california'],
                ['us_west_oregon','us_west_oregon']
              ], {},  :class => 'form-control'
            %>
          </div>

          <div class="form-group">
            <%= f.label :encoder %><br>
            <%= f.select :encoder, [['other_rtmp','other_rtmp'], ['other_rtsp','other_rtsp']], {}, :class => 'form-control'  %>
          </div>

          <div class="form-group">
            <%= f.label :delivery_method %><br>
            <%= f.select :delivery_method, [['push','push']], {},  :class => 'form-control'  %>
          </div>

          <div class="form-group">
            <%= f.label :aspect_ratio_width %><br>
            <%= f.text_field :aspect_ratio_width, :value => '1920', :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :aspect_ratio_height %><br>
            <%= f.text_field :aspect_ratio_height, :value => '1080', :class => 'form-control'  %>
          </div>

          <div class="form-group">
            <%= f.submit 'Set Stream', :class => 'btn btn-primary'  %>
          </div>
        <% end %>
      </div>
    </div>
</div>